class UserTextTranse {
  List<String> listTransleatArabick = [
    "ترك",
    "قدرة",
    "قادر",
    "حول",
    "فوق",
    "في الخارج",
    "غياب",
    "مطلق",
    "تماماً",
    "امتصاص",
    "سوء",
    "أكاديمي",
    "قبول",
    "الوصول",
    "حادث",
    "يرافق",
    "إنجاز",
    "وفقًا لـ",
    "حساب",
    "دقيق",
    "اتهام",
    "تحقيق",
    "إنجاز",
    "حمض",
    "اعترف",
    "اكتساب",
    "عبر",
    "فعل",
    "عمل",
    "فاعل",
    "نشاط",
    "ممثل",
    "ممثلة",
    "فعلي",
    "فعلياً",
    "إعلان",
    "تكيف",
    "إضافة",
    "إضافة",
    "إضافية",
    "عنوان",
    "كاف",
    "ضبط",
    "ضبط",
    "إدارة",
    "مدير",
    "أعجب",
    "قبول",
    "اعتراف",
    "مراهق",
    "تبنى",
    "بالغ",
    "تقدم",
    "متقدم",
    "ميزة",
    "مغامرة",
    "إعلان",
    "نصيحة",
    "نصح",
    "مستشار",
    "مدافع",
    "شؤون",
    "تؤثر",
    "تحمل",
    "خائف",
    "أفريقي",
    "أمريكي من أصل أفريقي",
    "بعد",
    "بعد الظهر",
    "مرة أخرى",
    "ضد",
    "عمر",
    "وكالة",
    "جدول أعمال",
    "وكيل",
    "عدوانية",
    "عدواني",
    "قبل",
    "الاتفاق",
    "اتصال",
    "حادث",
    "مصاحب",
    "إنجاز",
    "وفقًا لـ",
    "حساب",
    "دقيق",
    "اتهام",
    "تحقيق",
    "إنجاز",
    "حمض",
    "اعترف",
    "اكتساب",
    "عبر",
    "فعل",
    "عمل",
    "فاعل",
    "نشاط",
    "ممثل",
    "ممثلة",
    "فعلي",
    "فعلياً",
    "إعلان",
    "تكيف",
    "إضافة",
    "إضافة",
    "إضافية",
    "عنوان",
    "كاف",
    "ضبط",
    "ضبط",
    "إدارة",
    "مدير",
    "أعجب",
    "قبول",
    "اعتراف",
    "مراهق",
    "تبنى",
    "بالغ",
    "تقدم",
    "متقدم",
    "ميزة",
    "مغامرة",
    "إعلان",
    "نصيحة",
    "نصح",
    "مستشار",
    "مدافع",
    "شؤون",
    "تؤثر",
    "تحمل",
    "خائف",
    "أفريقي",
    "أمريكي من أصل أفريقي",
    "بعد",
    "بعد الظهر",
    "مرة أخرى",
    "ضد",
    "عمر",
    "وكالة",
    "جدول أعمال",
    "وكيل",
    "عدوانية",
    "عدواني",
    "قبل",
    "الاتفاق",
    "اتصال",
    "حادث",
    "مصاحب",
    "إنجاز",
    "وفقًا لـ",
    "حساب",
    "دقيق",
    "اتهام",
    "تحقيق",
    "إنجاز",
    "حمض",
    "اعترف",
    "اكتساب",
    "عبر",
    "فعل",
    "عمل",
    "فاعل",
    "نشاط",
    "ممثل",
    "ممثلة",
    "فعلي",
    "فعلياً",
    "إعلان",
    "تكيف",
    "إضافة",
    "إضافة",
    "إضافية",
    "عنوان",
    "كاف",
    "ضبط",
    "ضبط",
    "إدارة",
    "مدير",
    "أعجب",
    "قبول",
    "اعتراف",
    "مراهق",
    "تبنى",
    "بالغ",
    "تقدم",
    "متقدم",
    "ميزة",
    "مغامرة",
    "إعلان",
    "نصيحة",
    "نصح",
    "مستشار",
    "مدافع",
    "شؤون",
    "تؤثر",
    "تحمل",
    "خائف",
    "أف"
  ];
  List<String> listTransleatEnglish = [
    "abandon",
    "ability",
    "able",
    "about",
    "above",
    "abroad",
    "absence",
    "absolute",
    "absolutely",
    "absorb",
    "abuse",
    "academic",
    "accept",
    "access",
    "accident",
    "accompany",
    "accomplish",
    "according",
    "account",
    "accurate",
    "accuse",
    "achieve",
    "achievement",
    "acid",
    "acknowledge",
    "acquire",
    "across",
    "act",
    "action",
    "active",
    "activist",
    "activity",
    "actor",
    "actress",
    "actual",
    "actually",
    "ad",
    "adapt",
    "add",
    "addition",
    "additional",
    "address",
    "adequate",
    "adjust",
    "adjustment",
    "administration",
    "administrator",
    "admire",
    "admission",
    "admit",
    "adolescent",
    "adopt",
    "adult",
    "advance",
    "advanced",
    "advantage",
    "adventure",
    "advertising",
    "advice",
    "advise",
    "adviser",
    "advocate",
    "affair",
    "affect",
    "afford",
    "afraid",
    "African",
    "African-American",
    "after",
    "afternoon",
    "again",
    "against",
    "age",
    "agency",
    "agenda",
    "agent",
    "aggression",
    "aggressive",
    "ago",
    "agree",
    "agreement",
    "agricultural",
    "ah",
    "ahead",
    "aid",
    "aide",
    "AIDS",
    "aim",
    "air",
    "aircraft",
    "airline",
    "airport",
    "album",
    "alcohol",
    "alive",
    "all",
    "alliance",
    "allow",
    "ally",
    "almost",
    "alone",
    "along",
    "already",
    "also",
    "alter",
    "alternative",
    "although",
    "always",
    "AM",
    "amazing",
    "American",
    "among",
    "amount",
    "analysis",
    "analyst",
    "analyze",
    "ancient",
    "and",
    "anger",
    "angle",
    "angry",
    "animal",
    "anniversary",
    "announce",
    "annual",
    "another",
    "answer",
    "anticipate",
    "anxiety",
    "any",
    "anybody",
    "anymore",
    "anyone",
    "anything",
    "anyway",
    "anywhere",
    "apart",
    "apartment",
    "apparent",
    "apparently",
    "appeal",
    "appear",
    "appearance",
    "apple",
    "application",
    "apply",
    "appoint",
    "appointment",
    "appreciate",
    "approach",
    "appropriate",
    "approval",
    "approve",
    "approximately",
    "Arab",
    "architect",
    "area",
    "argue",
    "argument",
    "arise",
    "arm",
    "armed",
    "army",
    "around",
    "arrange",
    "arrangement",
    "arrest",
    "arrival",
    "arrive",
    "art",
    "article",
    "artist",
    "artistic",
    "as",
    "Asian",
    "aside",
    "ask",
    "asleep",
    "aspect",
    "assault",
    "assert",
    "assess",
    "assessment",
    "asset",
    "assign",
    "assignment",
    "assist",
    "assistance",
    "assistant",
    "associate",
    "association",
    "assume",
    "assumption",
    "assure",
    "at",
    "athlete",
    "athletic",
    "atmosphere",
    "attach",
    "attack",
    "attempt",
    "attend",
    "attention",
    "attitude",
    "attorney",
    "attract",
    "attraction",
    "attractive",
    "attribute",
    "audience",
    "author",
    "authority",
    "auto",
    "available",
    "average",
    "avoid",
    "award",
    "aware",
    "awareness",
    "away",
    "awful",
    "baby",
    "back",
    "background",
    "bad",
    "badly",
    "bag",
    "bake",
    "balance",
    "ball",
    "ban",
    "band",
    "bank",
    "bar",
    "barely",
    "barrel",
    "barrier",
    "base",
    "baseball",
    "basic",
    "basically",
    "basis",
    "basket",
    "basketball",
    "bathroom",
    "battery",
    "battle",
    "be",
    "beach",
    "bean",
    "bear",
    "beat",
    "beautiful",
    "beauty",
    "because",
    "become",
    "bed",
    "bedroom",
    "beer",
    "before",
    "begin",
    "beginning",
    "behavior",
    "behind",
    "being",
    "belief",
    "believe",
    "bell",
    "belong",
    "below",
    "belt",
    "bench",
    "bend",
    "beneath",
    "benefit",
    "beside",
    "besides",
    "best",
    "bet",
    "better",
    "between",
    "beyond",
    "Bible",
    "big",
    "bike",
    "bill",
    "billion",
    "bind",
    "biological",
    "bird",
    "birth",
    "birthday",
    "bit",
    "bite",
    "black",
    "blade",
    "blame",
    "blanket",
    "blind",
    "block",
    "blood",
    "blow",
    "blue",
    "board"
  ];
  List<String> wordsJopInterviewArabick = [
    "مقابلة",
    "عمل",
    "مرشح",
    "صاحب",
    "عمل",
    "سيرة",
    "ذاتية",
    "رسالة",
    "تغطية",
    "مهارات",
    "خبرة",
    "مؤهلات",
    "تعليم",
    "خلفية",
    "مراجع",
    "إنجازات",
    "أهداف",
    "قوى",
    "ضعف",
    "فرص",
    "تحديات",
    "نجاحات",
    "فشل",
    "توقعات",
    "راتب",
    "فوائد",
    "ثقافة",
    "فريق",
    "دور",
    "مسؤوليات",
    "مهام",
    "مشاريع",
    "نتائج",
    "أداء",
    "تغذية",
    "راجعة",
    "تحسين",
    "تدريب",
    "تطوير",
    "مسار",
    "وظيفي",
    "طموحات",
    "دافع",
    "شغف",
    "تفاني",
    "التزام",
    "احترافية",
    "تواصل",
    "بيئة",
    "شغل",
    "تحليل",
    "تصميم",
    "تقديم",
    "استقبال",
    "سلوكية",
    "أسئلة",
    "تقنية",
    "دراسة",
    "حالة",
    "تقييم",
    "تقدير",
    "اختيار",
    "رفض",
    "عرض",
    "تفاوض",
    "تدريب",
    "تأهيل",
    "توجيه",
    "إشراف",
    "تقييم",
    "أداء",
    "تقديم",
    "استقالة",
    "خروج",
    "احترافية",
    "أخلاق",
    "تصرف",
    "ملابس",
    "لغة",
    "جسد",
    "مصافحة",
    "اتصال",
    "عين",
    "ابتسامة",
    "ثقة",
    "إعداد",
    "بحث",
    "أسئلة",
    "إجابات",
    "متابعة",
    "شكر",
    "شبكة",
    "إحالة",
    "توظيف",
    "تعيين",
    "اختيار",
    "تجميع",
    "فحص",
    "استفسار",
    "عرض",
    "مفاوضة",
    "التوظيف",
    "توجيه",
    "مهمة",
    "تقييم",
    "أداء",
    "تقديم",
    "استقالة",
    "خروج",
    "مهارات",
    "تواصل",
    "بين",
    "شخصي",
    "تقنية",
    "ناعمة",
    "صلبة",
    "إدارة",
    "وقت",
    "منظمة",
    "انتباه",
    "للتفاصيل",
    "إدارة",
    "الضغط",
    "علاقات",
    "بين",
    "الأشخاص",
    "حل",
    "المشكلات",
    "اتخاذ",
    "القرارات",
    "قيادة",
    "عمل",
    "جماعي",
    "حل",
    "النزاعات",
    "التكيف",
    "مرونة",
    "إبداع",
    "مبادرة",
    "إدارة",
    "الوقت",
    "مهارات",
    "تنظيمية",
    "انتباه",
    "للتفاصيل",
    "إدارة",
    "الضغط",
    "إدارة",
    "الضغط",
    "مهارات",
    "تفاوض",
    "حل",
    "النزاعات",
    "مهارات",
    "فريق"
  ];
  List<String> wordsJopInterviewEnglish = [
    "Interview",
    "work",
    "candidate",
    "employer",
    "job",
    "resume",
    "cover letter",
    "skills",
    "experience",
    "qualifications",
    "education",
    "background",
    "references",
    "achievements",
    "goals",
    "strengths",
    "weaknesses",
    "opportunities",
    "challenges",
    "successes",
    "failures",
    "expectations",
    "salary",
    "benefits",
    "culture",
    "team",
    "role",
    "responsibilities",
    "tasks",
    "projects",
    "results",
    "performance",
    "feedback",
    "review",
    "improvement",
    "training",
    "development",
    "career path",
    "aspirations",
    "motivation",
    "passion",
    "dedication",
    "commitment",
    "professionalism",
    "communication",
    "environment",
    "employment",
    "analysis",
    "design",
    "presentation",
    "reception",
    "behavioral",
    "questions",
    "technical",
    "study",
    "case",
    "evaluation",
    "appraisal",
    "selection",
    "rejection",
    "offer",
    "negotiation",
    "training",
    "qualification",
    "guidance",
    "supervision",
    "performance",
    "presentation",
    "resignation",
    "exit",
    "professionalism",
    "ethics",
    "behavior",
    "clothing",
    "language",
    "body",
    "handshake",
    "contact",
    "eye",
    "smile",
    "confidence",
    "preparation",
    "research",
    "questions",
    "answers",
    "follow-up",
    "thanks",
    "network",
    "referral",
    "recruitment",
    "appointment",
    "selection",
    "compilation",
    "inspection",
    "inquiry",
    "offer",
    "negotiation",
    "recruitment",
    "guidance",
    "task",
    "performance",
    "career advancement",
    "termination",
    "work",
    "resignation",
    "exit",
    "skills",
    "personal",
    "technical",
    "soft",
    "hard",
    "time management",
    "organization",
    "attention to detail",
    "pressure management",
    "relationships",
    "problem solving",
    "decision making",
    "leadership",
    "teamwork",
    "conflict resolution",
    "adaptation",
    "flexibility",
    "creativity",
    "initiative",
    "time management",
    "organizational skills",
    "attention to detail",
    "pressure management",
    "pressure management",
    "negotiation skills",
    "conflict resolution",
    "team skills"
  ];
  List<String> wordsJobhuntingArabic = [
    "البحث عن العمل",
    "التوظيف",
    "السيرة الذاتية",
    "المقابلة",
    "فرص العمل",
    "المهنة",
    "الوظيفة المثالية",
    "عملية التقديم",
    "رسالة التغطية",
    "السيرة الذاتية",
    "الشبكات",
    "معرض الوظائف",
    "سوق العمل",
    "مجموعة المهارات",
    "الخبرة المهنية",
    "تاريخ العمل",
    "قائمة الوظائف",
    "لوحة الوظائف",
    "تحضير المقابلة الوظيفية",
    "طلب العمل",
    "عملية التوظيف",
    "الباحث عن عمل",
    "فتح الوظائف",
    "التوظيف",
    "وكالة التوظيف",
    "توظيف الوظائف",
    "تطوير المهنة",
    "التقدم المهني",
    "آفاق العمل",
    "رضا الوظيفي",
    "خبرة العمل",
    "معرض الوظائف",
    "التدريب التقني",
    "الوظيفة بدوام جزئي",
    "الوظيفة بدوام كامل",
    "الوظيفة المؤقتة",
    "الوظيفة الدائمة",
    "الوظيفة عن بعد",
    "العمل الحر",
    "العمل عن بعد",
    "العمل من المنزل",
    "وصف الوظيفة",
    "عنوان الوظيفة",
    "مفاوضة الراتب",
    "حزمة الفوائد",
    "التعويض",
    "فوائد الموظفين",
    "عملية الطلب",
    "استراتيجية البحث عن عمل",
    "موقع الوظائف",
    "بوابة الوظائف",
    "أسئلة المقابلة الوظيفية",
    "نصائح المقابلة الوظيفية",
    "تقنيات المقابلة الوظيفية",
    "آداب المقابلة الوظيفية",
    "المقابلة السلوكية",
    "المقابلة القائمة على المهارات",
    "المقابلة الجماعية",
    "المقابلة الهاتفية",
    "المقابلة عبر الفيديو",
    "المقابلة عن بعد",
    "المقابلة شخصيًا",
    "المقابلة الثانية",
    "متابعة بعد المقابلة",
    "عرض العمل",
    "عقد العمل",
    "اتفاقية العمل",
    "توجيه الوظيفة",
    "فترة الاختبار",
    "التكييف",
    "التوجيه",
    "التدريب المهني",
    "تطوير المهارات",
    "الشهادة المهنية",
    "التعليم المستمر",
    "تقييم المهنة",
    "التوجيه المهني",
    "الانتقال المهني",
    "تغيير المهنة",
    "المسار المهني",
    "استطلاع رضا الوظيفة",
    "التزام الموظفين",
    "توازن العمل والحياة",
    "ثقافة العمل",
    "الاحتفاظ بالموظفين",
    "تحول الوظيفة",
    "إجهاد الوظيفة",
    "حرق الوظيفة",
    "أمان الوظيفة",
    "فصل العمل",
    "إنهاء الخدمة",
    "الاستقالة",
    "الاستقالة الطوعية",
    "التقاعد",
    "فوائد البطالة",
    "مساعدة البحث عن عمل",
    "موقع البحث عن عمل",
    "محرك البحث عن عمل",
    "منصة البحث عن عمل",
    "تطبيق البحث عن عمل",
    "الشبكة الاجتماعية للبحث عن عمل",
    "السوق العملية الخفية",
    "الاتصال البارد",
    "المقابلة المعلوماتية",
    "مرافقة الوظيفة",
    "الشبكة في معرض الوظائف",
    "الجمعية المهنية",
    "شبكة الخريجين",
    "برنامج الإحالة",
    "الإحالة من قبل الموظفين",
    "تسويق الشخصي",
    "الحضور عبر الإنترنت",
    "الملف الشخصي على لينكدإن",
    "الحضور عبر وسائل التواصل الاجتماعي",
    "الشبكة المهنية",
    "حدث مهني",
    "ورشة عمل مهنية",
    "ندوة مهنية",
    "موارد مهنية",
    "إرشاد مهني",
    "الموعد النهائي لتقديم الطلبات",
    "حالة التقديم للعمل",
    "الجدول الزمني للبحث عن عمل",
    "قائمة التحقق للبحث عن عمل",
    "مخطط البحث عن عمل",
    "جدول بيانات البحث عن عمل",
    "سجل البحث عن عمل",
    "متتبع البحث عن عمل",
    "تنبيه البحث عن عمل",
    "إشعار البحث عن عمل",
    "فلتر البحث عن عمل",
    "معايير البحث عن عمل",
    "موقع البحث عن عمل",
    "صناعة البحث عن عمل",
    "راتب البحث عن عمل",
    "فوائد البحث عن عمل",
    "شركة البحث عن عمل",
    "ثقافة البحث عن عمل",
    "سمعة البحث عن عمل",
    "تقييمات البحث عن عمل",
    "تعليقات البحث عن عمل",
    "نصائح البحث عن عمل",
    "نصائح البحث عن عمل",
    "إرشادات البحث عن عمل",
    "ممارسات أفضل للبحث عن عمل",
    "نجاح البحث عن عمل",
    "استراتيجيات البحث عن عمل",
    "تكتيكات البحث عن عمل",
    "تقنيات البحث عن عمل",
    "أساليب البحث عن عمل",
    "موارد البحث عن عمل",
    "أدوات البحث عن عمل",
    "مواقع البحث عن عمل",
    "منصات البحث عن عمل",
    "تطبيقات البحث عن عمل",
    "مجتمعات البحث عن عمل",
    "منتديات البحث عن عمل",
    "مجموعات البحث عن عمل",
    "فعاليات البحث عن عمل",
    "ندوات البحث عن عمل",
    "بودكاست البحث عن عمل",
    "مقالات البحث عن عمل",
    "مدونات البحث عن عمل",
    "فيديوهات البحث عن عمل",
    "دورات البحث عن عمل",
    "تدريب البحث عن عمل",
    "ورش العمل للبحث عن عمل",
    "توجيه البحث عن عمل",
    "توجيه البحث عن عمل",
    "دعم البحث عن عمل",
    "مساعدة البحث عن عمل",
    "استشارة البحث عن عمل",
    "خدمة البحث عن عمل",
    "وكالة البحث عن عمل",
    "منظمة البحث عن عمل",
    "برنامج البحث عن عمل",
    "مبادرة البحث عن عمل",
    "حملة البحث عن عمل",
    "مهمة البحث عن عمل",
    "رؤية البحث عن عمل",
    "هدف البحث عن عمل",
    "هدف البحث عن عمل",
    "هدف البحث عن عمل",
    "خطة البحث عن عمل",
    "استراتيجية البحث عن عمل",
    "نهج البحث عن عمل",
    "طريقة البحث عن عمل",
    "عملية البحث عن عمل",
    "نظام البحث عن عمل",
    "إطار البحث عن عمل",
    "نموذج البحث عن عمل",
    "البحث عن البحث عن عمل",
    "صيغة البحث عن عمل",
    "معادلة البحث عن عمل",
    "نمط البحث عن عمل",
    "بنية البحث عن عمل",
    "تنظيم البحث عن عمل",
    "تنسيق البحث عن عمل",
    "إدارة البحث عن عمل",
    "تنفيذ البحث عن عمل"
  ];
  List<String> wordsJobhuntingEnglish = [
    "Job search",
    "Employment",
    "Resume",
    "Interview",
    "Job opportunities",
    "Occupation",
    "Ideal job",
    "Application process",
    "Cover letter",
    "Curriculum vitae",
    "CV",
    "Networking",
    "Career fair",
    "Job market",
    "Skill set",
    "Professional experience",
    "Employment history",
    "Job listing",
    "Job board",
    "Job interview preparation",
    "Job application",
    "Hiring process",
    "Job seeker",
    "Job opening",
    "Recruitment",
    "Employment agency",
    "Job placement",
    "Career development",
    "Career advancement",
    "Employment prospects",
    "Job satisfaction",
    "Work experience",
    "Job fair",
    "Internship",
    "Part-time job",
    "Full-time job",
    "Temporary job",
    "Permanent job",
    "Remote job",
    "Freelancing",
    "Telecommuting",
    "Work-from-home",
    "Job description",
    "Job title",
    "Salary negotiation",
    "Benefits package",
    "Compensation",
    "Employee benefits",
    "Job application process",
    "Job search strategy",
    "Employment website",
    "Job portal",
    "Job interview questions",
    "Job interview tips",
    "Job interview techniques",
    "Job interview etiquette",
    "Behavioral interview",
    "Competency-based interview",
    "Panel interview",
    "Telephone interview",
    "Video interview",
    "Remote interview",
    "In-person interview",
    "Second interview",
    "Follow-up after interview",
    "Job offer",
    "Job contract",
    "Employment agreement",
    "Job orientation",
    "Probation period",
    "Onboarding",
    "Career coaching",
    "Job training",
    "Skills development",
    "Professional certification",
    "Continuing education",
    "Career assessment",
    "Career counseling",
    "Career transition",
    "Career change",
    "Career path",
    "Job satisfaction survey",
    "Employee engagement",
    "Work-life balance",
    "Workplace culture",
    "Employee retention",
    "Job turnover",
    "Job stress",
    "Job burnout",
    "Job security",
    "Layoff",
    "Termination",
    "Resignation",
    "Voluntary resignation",
    "Retirement",
    "Unemployment benefits",
    "Job search assistance",
    "Job search website",
    "Job search engine",
    "Job search platform",
    "Job search app",
    "Job search networking",
    "Hidden job market",
    "Cold calling",
    "Informational interview",
    "Job shadowing",
    "Job fair networking",
    "Professional association",
    "Alumni network",
    "Referral program",
    "Employee referral",
    "Personal branding",
    "Online presence",
    "LinkedIn profile",
    "Social media presence",
    "Professional networking",
    "Career event",
    "Career workshop",
    "Career seminar",
    "Career resources",
    "Career guidance",
    "Job application deadline",
    "Job application status",
    "Job search timeline",
    "Job search checklist",
    "Job search planner",
    "Job search spreadsheet",
    "Job search log",
    "Job search tracker",
    "Job search alert",
    "Job search notification",
    "Job search filter",
    "Job search criteria",
    "Job search location",
    "Job search industry",
    "Job search salary",
    "Job search benefits",
    "Job search company",
    "Job search culture",
    "Job search reputation",
    "Job search reviews",
    "Job search feedback",
    "Job search tips",
    "Job search advice",
    "Job search guidance",
    "Job search best practices",
    "Job search success",
    "Job search strategies",
    "Job search tactics",
    "Job search techniques",
    "Job search methods",
    "Job search resources",
    "Job search tools",
    "Job search websites",
    "Job search platforms",
    "Job search apps",
    "Job search communities",
    "Job search forums",
    "Job search groups",
    "Job search events",
    "Job search webinars",
    "Job search podcasts",
    "Job search articles",
    "Job search blogs",
    "Job search videos",
    "Job search courses",
    "Job search training",
    "Job search workshops",
    "Job search coaching",
    "Job search mentoring",
    "Job search support",
    "Job search assistance",
    "Job search consultancy",
    "Job search service",
    "Job search agency",
    "Job search organization",
    "Job search program",
    "Job search initiative",
    "Job search campaign",
    "Job search mission",
    "Job search vision",
    "Job search goal",
    "Job search target",
    "Job search objective",
    "Job search plan",
    "Job search strategy",
    "Job search approach",
    "Job search method",
    "Job search process",
    "Job search system",
    "Job search framework",
    "Job search model",
    "Job search algorithm",
    "Job search formula",
    "Job search equation",
    "Job search pattern",
    "Job search structure",
    "Job search organization",
    "Job search coordination",
    "Job search management",
    "Job search execution"
  ];
  List<String> wordsOverthinkingArabic = [
    "تفكير",
    "تأمل",
    "تفكر",
    "تأمل",
    "تأمل",
    "تأمل",
    "تأمل",
    "تفكير",
    "تأمل",
    "تحليل",
    "فحص",
    "تحليل",
    "نقد",
    "تقييم",
    "مراجعة",
    "نظر",
    "وزن",
    "مناقشة",
    "تفكير",
    "استنتاج",
    "قرار",
    "اختيار",
    "تخطيط",
    "تنبؤ",
    "تنبؤ",
    "توقع",
    "تصور",
    "تخيل",
    "تصور",
    "تخيل",
    "تخيل",
    "قلق",
    "هاجس",
    "تملك",
    "السكن",
    "التفكير",
    "تأمل",
    "الفلسفة",
    "التفكير",
    "تأمل",
    "ثقيل",
    "تفكير",
    "تأمل",
    "تفكير",
    "تأمل",
    "تأمل",
    "تفكير",
    "تفكير",
    "تحليل",
    "فحص",
    "تحليل",
    "نقد",
    "تقييم",
    "مراجعة",
    "نظر",
    "وزن",
    "مناقشة",
    "تفكير",
    "استنتاج",
    "قرار",
    "اختيار",
    "تصميم",
    "خطة",
    "تنبؤ",
    "تنبؤ",
    "توقع",
    "تصور",
    "تخيل",
    "تصور",
    "تخيل",
    "تخيل",
    "قلق",
    "هاجس",
    "تملك",
    "السكن",
    "التفكير",
    "تأمل",
    "الفلسفة",
    "التفكير",
    "تأمل",
    "ثقيل",
    "تفكير",
    "تأمل",
    "تفكير",
    "تأمل",
    "تأمل",
    "تفكير",
    "تفكير",
    "تحليل",
    "فحص",
    "تحليل",
    "نقد",
    "تقييم",
    "مراجعة",
    "نظر",
    "وزن",
    "مناقشة",
    "تفكير",
    "استنتاج",
    "قرار",
    "اختيار",
    "تصميم",
    "خطة",
    "تنبؤ",
    "تنبؤ",
    "توقع",
    "تصور",
    "تخيل",
    "تصور",
    "تخيل",
    "تخيل",
    "قلق",
    "هاجس",
    "تملك",
    "السكن",
    "التفكير",
    "تأمل",
    "الفلسفة",
    "التفكير",
    "تأمل",
    "ثقيل",
    "تفكير",
    "تأمل",
    "تفكير",
    "تأمل",
    "تأمل",
    "تفكير",
    "تفكير",
    "تحليل",
    "فحص",
    "تحليل",
    "نقد",
    "تقييم",
    "مراجعة",
    "نظر",
    "وزن",
    "مناقشة",
    "تفكير",
    "استنتاج",
    "قرار",
    "اختيار",
    "تصميم",
    "خطة",
    "تنبؤ",
    "تنبؤ",
    "توقع",
    "تصور",
    "تخيل",
    "تصور",
    "تخيل",
    "تخيل",
    "قلق",
    "هاجس",
    "تملك",
    "السكن",
    "التفكير",
    "تأمل",
    "الفلسفة",
    "التفكير",
    "تأمل",
    "ثقيل"
  ];
  List<String> wordsOverthinkingEnglish = [
    "Reflective",
    "introspective",
    "philosophizing",
    "rumination",
    "ponderous",
    "ratiocination",
    "cognitive",
    "intellectualizing",
    "conjecture",
    "mulling",
    "circumspection",
    "exploratory",
    "examination",
    "scrutiny",
    "critical",
    "assessment",
    "appraisal",
    "deliberation",
    "ponder",
    "logic",
    "conclusion",
    "resolution",
    "selection",
    "strategy",
    "foresight",
    "projection",
    "forecast",
    "prediction",
    "anticipation",
    "envision",
    "imagination",
    "visualization",
    "daydream",
    "fantasy",
    "anxiety",
    "obsession",
    "preoccupation",
    "dwelling",
    "brood",
    "worry",
    "angst",
    "fixation",
    "ratiocinate",
    "introspection",
    "philosophize",
    "ruminate",
    "ponderous",
    "reflection",
    "meditation",
    "cogitate",
    "speculation",
    "deliberation",
    "examination",
    "scrutiny",
    "analysis",
    "critique",
    "evaluation",
    "review",
    "consideration",
    "weighing",
    "debate",
    "reasoning",
    "conclusion",
    "decision-making",
    "choice",
    "design",
    "plan",
    "forecasting",
    "predictive",
    "foreseeing",
    "imaginative",
    "visual",
    "visualization",
    "daydreaming",
    "fantasizing",
    "concern",
    "obsession",
    "preoccupation",
    "dwelling",
    "brooding",
    "ruminative",
    "anxious",
    "overanalytical",
    "rumination",
    "introspection",
    "philosophizing",
    "ruminative",
    "pondering",
    "reflection",
    "meditation",
    "cogitation",
    "speculation",
    "deliberation",
    "examination",
    "scrutiny",
    "analysis",
    "critique",
    "evaluation",
    "review",
    "consideration",
    "weighing",
    "debate",
    "reasoning",
    "conclusion",
    "decision-making",
    "choice",
    "planning",
    "forecasting",
    "predictive",
    "foreseeing",
    "imaginative",
    "visual",
    "visualization",
    "daydreaming",
    "fantasizing",
    "concern",
    "obsession",
    "preoccupation",
    "dwelling",
    "brooding",
    "ruminative",
    "anxious",
    "overanalytical",
    "pondering",
    "reflection",
    "meditation",
    "cogitation",
    "speculation",
    "deliberation",
    "examination",
    "scrutiny",
    "analysis",
    "critique",
    "evaluation",
    "review",
    "consideration",
    "weighing",
    "debate",
    "reasoning",
    "conclusion",
    "decision-making",
    "choice",
    "planning",
    "forecasting",
    "predictive",
    "foreseeing",
    "imaginative",
    "visual",
    "visualization",
    "daydreaming",
    "fantasizing",
    "concern",
    "obsession",
    "preoccupation",
    "dwelling",
    "brooding",
    "ruminative",
    "anxious",
    "overanalytical"
  ];
  List<String> PopularexamplesArabick = [
    "كما يقولون، الأفعال تتحدث بصوت أعلى من الكلمات",
    "تكلفة باهظة جدًا",
    "العودة إلى نقطة البداية",
    "التوجه نحو الهدف الخطأ",
    "تفادي الحديث المباشر",
    "المواجهة الصعبة بشجاعة",
    "حظًا سعيدًا",
    "بأعجوبة",
    "بشدة أو بصعوبة",
    "بأقل التكاليف الممكنة",
    "الاستغناء عن الجودة من أجل السرعة",
    "عدم الندم على ما فات",
    "لكل شيء جانب إيجابي",
    "تجربة تذوق نكهة أفعالك",
    "استقبال نتيجة أفعالك الخاصة",
    "تقديم الشجاعة في الوقت الصعب",
    "بأقل الفوارق",
    "تسمح للقط بالخروج من الكيس",
    "فوات الفرصة",
    "نادرًا ما يحدث",
    "سهل كالقطعة من الكعك",
    "إخافة الآخرين للتسلية",
    "تساقط الأمطار بغزارة",
    "النجاة بأعجوبة من المواقف الصعبة",
    "الكشف عن الأسرار",
    "يكمن الأمر الآن في يدك",
    "التعامل مع الأمور المالية أو الشخصية",
    "قصر النظر في المواقف",
    "تفادي القدر المحتوم",
    "عدم الندم على الماضي",
    "استمرار العمل الثابت",
    "عدم وضع كل الأمل في شيء واحد",
    "عدم العجلة بالقرارات",
    "القضايا الكبيرة غالباً ما تكون صعبة",
    "إضافة قيمة",
    "السماح للغريب بالمشاركة في مجموعتك",
    "المصاعب تجلب الخبرة",
    "تجنب المشاكل",
    "القدرة على كسر الجليد",
    "عدم تجاوز الحدود في المقارنة",
    "تكلفة باهظة",
    "تحمل المسؤولية في النهاية",
    "عدم اليأس من التحدّيات",
    "الواقعية في النظر للأمور",
    "تجاهل الأمور الصعبة",
    "الفائدة القصوى",
    "القشة التي قلبت الميزان",
    "الاستعداد للمواجهة",
    "الواقعية في النظر للأمور",
    "قضاء الوقت بالتركيز على الأهداف",
    "الكلام مباشرة دون تحجيم",
    "دور الشخص الذي يتبنى الفكرة المعاكسة",
    "عدم التكاسل وراء الظروف",
    "عدم اليأس من المستقبل",
    "تقدير الجهود المبذولة",
    "التعبير عن الاهتمام الحقيقي",
    "التصدي للصعاب",
    "استعداد لتحمل عواقب القرارات",
    "التكافؤ بين الفرص",
    "تقديم المساعدة بروح الفريق",
    "القدرة على تخطي الصعاب",
    "تحقيق النجاح بصبر وإصرار",
    "التغلب على الصعاب بالشجاعة",
    "التركيز على الجوانب الإيجابية",
    "قبول التحدي بالشجاعة",
    "العمل الشاق للوصول إلى الهدف",
    "الاجتهاد والعمل الجاد لتحقيق النجاح",
    "الصبر والعمل الجاد للتغلب على العقبات",
    "التفاني في العمل للوصول إلى النجاح",
    "تحقيق الأحلام بالإرادة والعمل الجاد",
    "اجتياز التحديات بالثقة والإيمان",
    "التحدي الصعب المؤلم والمرير",
    "التحلي بالقوة والصبر في مواجهة الصعاب",
    "تجاوز العوائق بالإصرار والعزيمة",
    "التمسك بالأمل والإيمان بالنجاح",
    "التغلب على الصعاب بالعزيمة والثقة",
    "التحلي بالصبر والاستمرار لتحقيق النجاح",
    "الثبات والإصرار في مواجهة التحديات",
    "الاجتهاد والاجتهاد لتحقيق النجاح",
    "التحلي بالثبات والقوة في التغلب على الصعوبات"
  ];
  List<String> PopularexamplesEnglish = [
    "Actions speak louder than words",
    "An arm and a leg",
    "Back to the drawing board",
    "Barking up the wrong tree",
    "Beat around the bush",
    "Bite the bullet",
    "Break a leg",
    "By the skin of your teeth",
    "Costs an arm and a leg",
    "Cutting corners",
    "Don't cry over spilled milk",
    "Every cloud has a silver lining",
    "Get a taste of your own medicine",
    "Get cold feet",
    "Give someone the cold shoulder",
    "Go the extra mile",
    "Hit the nail on the head",
    "Let the cat out of the bag",
    "Miss the boat",
    "Once in a blue moon",
    "Piece of cake",
    "Pull someone's leg",
    "Raining cats and dogs",
    "Saved by the bell",
    "Spill the beans",
    "The ball is in your court",
    "The best of both worlds",
    "The last straw",
    "Throw in the towel",
    "Under the weather",
    "When pigs fly",
    "A penny for your thoughts",
    "A picture is worth a thousand words",
    "Actions speak louder than words",
    "Add insult to injury",
    "An arm and a leg",
    "At the drop of a hat",
    "Back to square one",
    "Barking up the wrong tree",
    "Beat around the bush",
    "Bite off more than you can chew",
    "Break the ice",
    "By the skin of your teeth",
    "Comparing apples to oranges",
    "Cost an arm and a leg",
    "Cross that bridge when you come to it",
    "Cry over spilled milk",
    "Cut corners",
    "Devil's advocate",
    "Don't count your chickens before they hatch",
    "Don't cry over spilled milk",
    "Don't give up your day job",
    "Don't put all your eggs in one basket",
    "Don't put the cart before the horse",
    "Elephant in the room",
    "Every cloud has a silver lining",
    "Far cry from",
    "Feather in one's cap",
    "Fish out of water",
    "Go down in flames",
    "Go out on a limb",
    "Grain of salt",
    "Have a chip on your shoulder",
    "Have eyes in the back of your head",
    "Hit the nail on the head",
    "Jump on the bandwagon",
    "Kick the bucket",
    "Let the cat out of the bag",
    "Like a moth to a flame",
    "Miss the boat",
    "Needle in a haystack",
    "On thin ice",
    "Once in a blue moon",
    "Piece of cake",
    "Pot calling the kettle black",
    "Put all your eggs in one basket",
    "Rain on someone's parade",
    "Raining cats and dogs",
    "Read between the lines",
    "Rule of thumb",
    "See eye to eye",
    "Selling like hotcakes",
    "Six of one, half a dozen of the other",
    "Speak of the devil",
    "Spill the beans",
    "Take it with a grain of salt",
    "Take the cake",
    "The ball is in your court",
    "The best of both worlds",
    "The devil is in the details",
    "The last straw",
    "The whole nine yards",
    "Throw in the towel",
    "Through thick and thin",
    "Toss-up",
    "Twist someone's arm",
    "Under the weather",
    "Up in the air",
    "You can't judge a book by its cover"
  ];
}
